services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: todoapp_web
    depends_on:
      - mysql
    environment:
      DB_USER: todo_user
      DB_PASSWORD: todo_pass
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: todo_db
    ports:
      - "8000:8000"
