services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-net

  web:
    build: .
    container_name: todoapp_web
    restart: on-failure
    depends_on:
      - mysql
    environment:
      DB_USER: todo_user
      DB_PASSWORD: todo_pass
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: todo_db
      PYTHONUNBUFFERED: "1"
    ports:
      - "80:8000"
    networks:
      - todo-net
      
  alloy:
    image: grafana/alloy:latest
    container_name: alloy-local
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    depends_on:
      - web
    networks:
      - todo-net

# Define the network here
networks:
  todo-net:
    driver: bridge
